M48
; DRILL file {KiCad (6.0.1)} date Sun Apr 16 16:50:23 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-16T16:50:23+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X6.6756Y-4.4657
X6.7965Y-4.6913
T2
X6.5319Y-4.3402
X6.6319Y-4.3402
T3
X6.0954Y-4.5941
X6.3907Y-4.5941
X6.757Y-4.5941
X7.0523Y-4.5941
T0
M30
