low_H = 0
high_H = 180
low_S = 0
high_S = 255
low_V = 68
high_V = 255
high_F = 255
count_threshold = 0
hue = 255
gain = 255
saturation = 255
morse_time = 120
boxes = [ [ 314, 110,], [ 317, 296,], [ 202, 224,],]
